name: boids
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.12
  - numpy=2.3.5
  - scipy=1.16.3
  - numba=0.63.1
  - vispy=0.14.3
  - ipykernel=7.1.0
  - ipython=9.8.0
  - matplotlib-inline=0.2.1
  - pyzmq=27.1.0
  - tornado=6.5.4
  - psutil=7.0.0
  - colorama=0.4.6
  - llvmlite=0.46.0
  - mkl=2025.0.0
  - openssl=3.6.0
  - pip
  - pip:
      - pybullet==3.2.7
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.2